name: GitHub Action to Azure using identity federation

on:
  push:
    branches:
      - main
  
  workflow_dispatch:
    
jobs:
  auth-azure:
    runs-on: ubuntu-latest
    permissions:
      id-token: write    
      contents: read
    steps:
      - name: 'Login to Azure with OIDC federated credentials'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      - name: Show success message
        run: echo "âœ… Successfully authenticated with Azure using federated credentials!"
      - name: 'Run az commands'
        run: |
          az account show           
          az account list-locations --query "[].{Name:name, DisplayName:displayName}" -o table
